config/routes.rb
UrlShorten::Application.routes.draw do
  resources :urls, :only => [:show, :new, :create]
  root :to => redirect('/urls/new')

end

app/models/url.rb
class Url < ActiveRecord::Base
  attr_accessible :url
  validates :url, :presence => true
  validates_format_of :url, :with => /^(http|https):\/\/[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,5}(:[0-9]{1,5})?(\/.*)?$/ix
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/urls_controller.rb
class UrlsController < ApplicationController
  def new
    @shortened_url = Url.new
  end
  
  def create
    @shortened_url = Url.new(params[:url])
    if @shortened_url.save
      flash[:shortened_id] = @shortened_url.id
      redirect_to new_url_url
    else
      render :action => :new
    end
  end
  
  def show
   @shortened_url = Url.find(params[:id])
   redirect_to @shortened_url.url 
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/urls_helper.rb
module UrlsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>UrlShorten</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<% if flash[:shortened_id].present? %>
  <p class='shortened-link'>
    The shortened url is available <%= link_to 'here', url_url(flash[:shortened_id]) %>.
    (Right click and copy link to share it).
  </p>
<% end %>
<%= yield %>

</body>
</html>

app/views/urls/new.html.erb
<h1>Add a new URL</h1>
<%= form_for @shortened_url do |form| %>
  <p>
    <%= form.label :url, "Your URL:" %>
    <%= form.text_field :url %>
  </p>
  <% if @shortened_url.errors[:url].any? %>
    <p class='error-messages'>
      The given url <%= @shortened_url.errors[:url].to_sentence %>.
    </p>
  <% end %>
  <p class='buttons'>
    <%= form.submit "Shorten my URL" %>
  </p>
<% end %>